WebCIT/Models/ErrorViewModel.cs
namespace WebCIT.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebCIT/Models/LoginViewModel.cs
namespace WebCIT.Models
{
    public class LoginViewModel
    {
        public string Login { get; set; }
        public string Password { get; set; }
    }
}

WebCIT/Models/UserRegistrationModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebCIT.Models
{
    public class UserRegistrationModel
    {
        [Required(ErrorMessage = "Введите логин")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Введите пароль")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Введите email")]
        [EmailAddress(ErrorMessage = "Введите корректный email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Выберите роль")]
        public string Role { get; set; }

        [Required(ErrorMessage = "Введите ФИО")]
        public string FIO { get; set; }

        [Required(ErrorMessage = "Введите номер телефона")]
        [Phone(ErrorMessage = "Введите корректный номер телефона")]
        public string NumberPhone { get; set; }

        public string? PasswordHash { get; set; }
    }
}

WebCIT/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebCIT.Api.TicketService;
using WebCIT.Classed.Ticket;
using WebCIT.Models;

namespace WebCIT.Controllers
{
    public class AdminController : Controller
    {
        private readonly TicketService _ticketService;

        public AdminController()
        {
            _ticketService = new TicketService("https://26.191.182.183:7215");
        }

        // Метод для отображения страницы с тикетами
        public async Task<IActionResult> AdminDashboard()
        {
            var tickets = await _ticketService.GetAllTicket();
            return View(tickets);
        }
    }
}

WebCIT/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebCIT.Models;

namespace WebCIT.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View("Login");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebCIT/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Net.Sockets;
using WebCIT.Api.AuthService;
using WebCIT.Api.TicketService;
using WebCIT.Classed.Ticket;

namespace WebCIT.Controllers
{
    public class TicketController: Controller
    {
        private readonly TicketService _ticketService;

        public TicketController()
        {
            _ticketService = new TicketService("https://26.240.38.124:7215");
        }

        public async Task<IActionResult> Details(int ID_Ticket)
        {
            Console.WriteLine($"Requesting ticket with ID: {ID_Ticket}");
            var ticket = await _ticketService.GetTicket(ID_Ticket);
            if (ticket == null)
            {
                Console.WriteLine($"Ticket with ID {ID_Ticket} not found.");
                return NotFound();
            }
            return View(ticket);
        }


        [HttpGet]
        public async Task<IActionResult> AdminDashboard(string searchQuery, string searchType, string searchStatus)
        {
            var ticket = await _ticketService.GetAllTicket();


            //---------------
            //Нужно исправить, т.к. в бд нет атрибутов AudienceNumber и BuildingNumber
            //

            //// Если запрос поиска не пустой, фильтруем тикеты
            //if (!string.IsNullOrEmpty(searchQuery))
            //{
            //    searchQuery = searchQuery.ToLower();
            //    ticket = ticket.Where(t =>
            //        t.AudienceNumber.ToLower().Contains(searchQuery) ||
            //        t.BuildingNumber.ToLower().Contains(searchQuery)
            //    ).ToList();
            //}


            // нужно исправить, т.к. в бд атрибут Type теперь int, нужно сделать выборку

            // Поиск тикетов по типу
            //if (!string.IsNullOrEmpty(searchType))
            //{
            //    searchType = searchType.ToLower();
            //    ticket = ticket.Where(t =>
            //    t.Type.Equals(searchType, StringComparison.OrdinalIgnoreCase))
            //        .ToList();
            //}


            if (!string.IsNullOrEmpty(searchStatus))
            {
                ticket = ticket
                    .Where(t => t.Status.Equals(searchStatus, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            }

            return View("~/Views/Admin/AdminDashboard.cshtml", ticket);
        }

        [HttpPost]
        public async  Task<IActionResult> RejectTicket(int id)
        {
            var ticket = await _ticketService.GetAllTicket();

            if (ticket == null)
            {
                return NotFound();
            }

            var existingTicket = ticket.FirstOrDefault(t => t.ID_Ticket == id);
            existingTicket.Status = "Отклонена";
            await _ticketService.UpdateStatus(existingTicket);
            return View("~/Views/Admin/AdminDashboard.cshtml", ticket);
        }

    }
}

WebCIT/Views/Admin/AdminDashboard.cshtml
@model List<WebCIT.Classed.Ticket.Ticket>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Панель администратора</title>
    <link rel="stylesheet" href="~/css/AdminDashboard.css">
</head>
<body>
    <div class="container">
        <h1>Панель администратора</h1>
        <h2>Список тикетов</h2>

      <div class="form-container">

        <!-- Форма поиска -->
        <form method="get" asp-controller="Ticket" asp-action="AdminDashboard">
            <input type="text" name="searchQuery" placeholder="Поиск по аудитории, корпусу" class="form-control" />
            <button type="submit" class="btn btn-primary">Найти</button>
        </form>

        <!-- Форма поиска по типу -->
        <form method="get" asp-controller="Ticket" asp-action="AdminDashboard">
            <select name="searchType" id="searchType" class="form-control">
                <option value="">Поиск по типу</option>
                <option value="Техническая">Техническая</option>
                <option value="Административная">Административная</option>
                <option value="Прочие">Прочие</option>
            </select>
            <button type="submit" class="btn btn-primary">Найти</button>
        </form>

        <!-- Форма поиска по статусу -->
        <form method="get" asp-controller="Ticket" asp-action="AdminDashboard">
            <select name="searchStatus" id="searchStatus" class="form-control">
                <option value="">Поиск по статусу</option>
                <option value="Открыта">Открыта</option>
                <option value="Завершена">Завершена</option>
                <option value="Новая">Новая</option>
                <option value="Отклонена">Отклонена</option>
            </select>
            <button type="submit" class="btn btn-primary">Найти</button>
        </form>
      </div>
        
        <table class="ticket-table">
            <table class="ticket-table">
                <thead>
                    <tr>
                        <th>Номер тикета</th>
                        <th>Номер корпуса</th> @*нужно исправить*@
                        <th>Номер аудитории</th> @*нужно исправить*@
                        <th>Автор</th>
                        <th>Тип</th>
                        @* <th>Описание</th> *@
                        <th>Дата создания</th>
                        @* <th>Исполнитель</th> *@
                        <th>Статус</th>
                        <th>Детали</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        foreach (var ticket in Model)
                        {
                            <tr>
                                <td>@ticket.ID_Ticket</td>
                                <td>@ticket.ID_Department</td> @*исправлено*@
                                <td>@ticket.Author</td>
                                <td>@ticket.Type</td>
                                @* <td>@ticket.Description</td> *@
                                <td>@ticket.DateOfCreation</td>
                                @* <td>@ticket.Executor</td> *@
                                <td>@ticket.Status</td>
                                <td><a href="@Url.Action("Details", "Ticket", new { ID_Ticket = ticket.ID_Ticket })" class="btn btn-secondary">Подробнее</a></td>
                            </tr>
                        }
                    }
                else
                {
                    <tr>
                        <td colspan="5">Нет доступных тикетов</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <nav>
        <div class="sidebar">

            <h1 class="sidebar-title">WebCIT</h1>

            <div class="menu-item">
                <img src="~/images/main/profile.svg" alt="Профиль">
            </div>
            <div class="menu-item">
                <img src="~/images/main/settings.svg" alt="Настройки">
            </div>
            <div class="menu-item">
                <img src="~/images/main/notifications.svg" alt="Уведомления">
            </div>
            <div class="menu-item">
                <img src="~/images/main/list.svg" alt="Отчеты">
            </div>

            <form method="get" asp-controller="User" asp-action="RegisterUser">
                <button type="submit" class="menu-item">
                    <img src="~/images/main/useradd.svg" alt="Зарегистрировать пользователя" />
                </button>
            </form>
        </div>
    </nav>
        <footer>
            <h3>
                Мы находимся в корпусе инженерного факультета, 518к <br>
                Режим работы: ежедневно, кроме субботы и воскресенья <br>
                с 9:00 до 17:00 Тел.: 30-65-50 <br>
                Copyright (c) 2007 - 2024 <br>
                Центр Информационных Технологий <br>
                ФГБОУ ВО Оренбургский ГАУ <br>
            </h3>
        </footer>

</body>

WebCIT/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebCIT/Views/Login/Login.cshtml
@model LoginViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>login</title>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <link rel="stylesheet" href="/css/login.css">
</head>
<body>
    <form asp-controller="AccountController" asp-action="Login" method="post">
        <div class="container">
            <div class="form-box">
                <div class="form-value">
                    <h2>Вход</h2>
                    <div class="inputbox">
                        <ion-icon name="person-circle-outline"></ion-icon>
                        <input asp-for="Login" type="text" required>
                        <label asp-for="Login">Логин</label>
                    </div>
                    <div class="inputbox">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                        <input asp-for="Password" type="password" required>
                        <label asp-for="Password">Пароль</label>
                    </div>
                    <button type="submit">Войти</button>
                    <div class="bottom">
                        <div class="left">
                            <input type="checkbox" id="check">
                            <label for="check">Запомнить меня</label>
                        </div>
                        <div class="right">
                            <label><a href="#">Я забыл пароль!</a></label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html> 

WebCIT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCIT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCIT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebCIT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebCIT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebCIT/Views/Ticket/Details.cshtml
@model WebCIT.Classed.Ticket.Ticket

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Детали тикета</title>
    <link rel="stylesheet" href="~/css/detailsticket.css"/>
</head>
<body>
    <div class="container">
        <h1>Панель администратора</h1>
        <h2>Подробности тикета</h2>

        @if (Model != null)
        {
            <table class="ticketDetails">
                <thead>
                    <tr>
                        <th>Номер тикета</th>
                        <th>Номер корпуса</th>  @*нужно исправить*@
                        <th>Номер аудитории</th> @*нужно исправить*@
                        <th>Автор</th>
                        <th>Тип</th>
                        <th>Дата создания</th>
                        <th>Статус</th>
                        <th>Дата завершения</th>
                        <th>Исполнитель</th>
                        <th>Описание</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.ID_Ticket</td>
                        <td>@Model.ID_Department</td> @*Исправленная часть*@
                        <td>@Model.Author</td>
                        <td>@Model.Type</td>
                        <td>@Model.DateOfCreation?.ToString("dd.MM.yyyy")</td>
                        <td>@Model.Status</td>
                        <td>@Model.DateOfCompletion?.ToString("dd.MM.yyyy")</td>
                        <td>@Model.Executor</td>
                        <td>@Model.Description</td>
                    </tr>
                </tbody>
            </table>
        }
        else
        {
            <p>Тикет не найден.</p>
        }

        <a href="@Url.Action("AdminDashboard", "Admin")" class="btn btn-secondary">Назад к списку тикетов</a>
    </div>
    
    @if (Model.Status != "Отклонена")
    {
        <form method="post" asp-action="RejectTicket" asp-controller="Ticket">
            <input type="hidden" name="id" value="@Model.ID_Ticket" />
            <button type="submit" class="btn btn-danger">Отклонить</button>
        </form>
    }

    <nav>
    <div class="sidebar">
        <h1 class="sidebar-title">WebCIT</h1>

        <div class="menu-item">
            <img src="~/images/main/profile.svg" alt="Профиль">
        </div>
        <div class="menu-item">
            <img src="~/images/main/settings.svg" alt="Настройки">
        </div>
        <div class="menu-item">
            <img src="~/images/main/notifications.svg" alt="Уведомления">
        </div>
        <div class="report-item">
            <img src="~/images/main/report.svg" alt="Отчеты">
        </div>
    </nav>
    </div>
    <footer>
        <h3>
            Мы находимся в корпусе инженерного факультета, 518к <br>
            Режим работы: ежедневно, кроме субботы и воскресенья <br>
            с 9:00 до 17:00 Тел.: 30-65-50 <br>
            Copyright (c) 2007 - 2024 <br>
            Центр Информационных Технологий <br>
            ФГБОУ ВО Оренбургский ГАУ <br>
        </h3>
    </footer>
</body>
</html>

WebCIT/Views/User/RegisterUser.cshtml
@model UserRegistrationModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация пользователя</title>
    <link rel="stylesheet" href="~/css/RegisterUser.css">
</head>
<body>
    <div class="container">
        <h1>Регистрация нового пользователя</h1>

        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success">
                @TempData["SuccessMessage"]
            </div>
        }

         <form asp-action="RegisterUser" asp-controller="User" method="post">
            <div class="form-group">
                <label for="Login">Логин</label>
                <input type="login" id="Login" name="Login" class="form-control" value="@Model?.Login" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="Password">Пароль</label>
                <input type="password" id="Password" name="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="Email">Email</label>
                <input type="email" id="Email" name="Email" class="form-control" value="@Model?.Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="Role">Роль</label>
                <select id="Role" name="Role" class="form-control">
                    <option value="">Выберите роль</option>
                    <option value="Администратор">Администратор</option>
                    <option value="Тех. Специалист">Тех. Специалист</option>
                    <option value="Сотрудник">Сотрудник</option>
                </select>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="FullName">ФИО</label>
                <input type="text" id="FIO" name="FIO" class="form-control" value="@Model?.FIO" />
                <span asp-validation-for="FIO" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="PhoneNumber">Номер телефона</label>
                <input type="tel" id="NumberPhone" name="NumberPhone" class="form-control" value="@Model?.NumberPhone" />
                <span asp-validation-for="NumberPhone" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Зарегистрировать</button>
            <a href="@Url.Action("AdminDashboard", "Ticket")" class="btn btn-secondary">Назад</a>
        </form>
    </div>  
    <nav>
        <div class="sidebar">

            <h1 class="sidebar-title">WebCIT</h1>

            <div class="menu-item">
                <img src="~/images/main/profile.svg" alt="Профиль">
            </div>
            <div class="menu-item">
                <img src="~/images/main/settings.svg" alt="Настройки">
            </div>
            <div class="menu-item">
                <img src="~/images/main/notifications.svg" alt="Уведомления">
            </div>
            <div class="menu-item">
                <img src="~/images/main/list.svg" alt="Отчеты">
            </div>
        </div>
    </nav>
</body>
</html>